### PR TITLE
Fixes for dev tidyselect

### PR DESCRIPTION
**Pull request by hadley**
We're now being a little stricter with inputs.

### CODE REVIEW

**Comment by michaelquinn32** [comment]
Thanks Hadley! Would you mind taking a look at the vignette too? That seems to be the source of the error in the checks.

**Comment by hadley** [comment]
Unfortunately I don't seem able to reproduce that locally.

**Comment by hadley** [comment]
Hmmm, works on oldrel-1 and fails on latest. I think this is what forces me to update R 😶

**Comment by hadley** [comment]
Ok, on 4.2 and can reproduce 😄

**Comment by hadley** [comment]
Took me a while to get to the root cause which was using `dplyr::groups()` instead of `dplyr::group_vars()` — `groups()` returns a list of symbols, which in many cases in R 4.1 or old tidyselect would automatically get coerced to a character vector. 

I also updated the docs to latest roxygen, updated the build script, and fixed another issue revealed by 4.2's check.

**Comment by michaelquinn32** [comment]
Oh man, didn't realize it was that big of a change.

Thank you so much!

**Pull request merged**
