### PR TITLE
Full(er) support for vctrs

### PR DESCRIPTION
**Pull request by michaelquinn32**

### CODE REVIEW

**Comment by elinw** [comment]
Should we link one of the resources in this comment rather than the issue discussion?
https://github.com/r-lib/vctrs/issues/982#issuecomment-622012072

**Comment by michaelquinn32** [comment]
Great point. Thank you!

**Comment by elinw** [comment]
@michaelquinn32 Is this branch ready to get merged?

**Comment by michaelquinn32** [comment]
Yes! I'll merge.

**Pull request merged**
