### PR TITLE
Add list as a class to skim_list objects.

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by elinw** [comment]
@michaelquinn32  I did this for a reason that I don't remember (it must have popped up as an issue when I was doing something), but it makes sense to me to add "list" in a second slot for the "skim_list"  objects.   But I don't see any problem with making tis change

**Comment by elinw** [comment]
I think it had to do with the issue about writing to xlsx, which for sure works better with a list.  But it's also good to do this anyway because then any function that applies to lists can be used.

**Comment by elinw** [comment]
@michaelquinn32  Are you okay with this?

**Comment by michaelquinn32** [comment]
Thanks for taking care of this.

**Pull request merged**
