### PR TITLE
Put skimmers in order when using focus().

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by michaelquinn32** [comment]
Hi Elin!

Thanks for taking this on.

I believe that a lot of this logic already exists in `reconcile_skimmers()`
https://github.com/ropensci/skimr/blob/97d0fa9f26c8e98912ba4079c44210f7bd88f382/R/reshape.R#L54

And the functionality is similar too. The point of that function is to make sure that columns and attributes are aligned. Is there a way to get everything working with that function?

Thanks!

**Comment by elinw** [comment]
Any thoughts?

**Comment by elinw** [comment]
@michaelquinn32 Any progress on this?  We should probably be thinking about a new release soon.

**Comment by michaelquinn32** [comment]
My PR is failing because of SF installation issues.

Otherwise, PTAL.

**Comment by elinw** [comment]
Ugh about sf, that's just supposed to be suggest ... maybe we should just stop with it. I think it's changed a lot anyway.

**Comment by michaelquinn32** [comment]
We could. I don't believe it to be a big deal either way. The reason sf failed is that a new version was released to cran, and we didn't have binaries.

**Comment by elinw** [comment]
Okay so I'm for merging, but I also think ... let's use a different example in the vignette.  It is simple to write a skim.lm method 
(that skims the lmresults$model)  so I can do that as the example (and also put in skimExtras.  Thoughts? @michaelquinn32

**Comment by michaelquinn32** [comment]
Thanks!

Merging now. I opened #675 to handle updating the vignette.

**Pull request merged**
