### PR TITLE
Check for spaces when removing metadata

### LINKED ISSUE #464: Grouped data: information about column types should be removed
The output of **grouped data** contains an unnecessary row with `<chr>` etc.
Is it a regression as this issue seemed to be solved in  #384?

From the examples of branch v2: https://github.com/ropensci/skimr/tree/v2
```r
iris %>%
    dplyr::group_by(Species) %>%
    skim()
```

image
image

Possibly related to #376, #384, #408.

### PR DESCRIPTION
**Pull request by michaelquinn32**
This handles bugs where certain kinds of metadata were appearing.

Closes #464

### CODE REVIEW

**Comment by elinw** [comment]
For
```
skim(dplyr::group_by(iris, Species))
```
I'm still getting the metadata in the console yet the test is passing.

**Comment by michaelquinn32** [comment]
Mind checking this again?

I did the following on a clean machine:

```
devtools::install_github("ropensci/skimr@v2-group-print")
library(skimr)
library(dplyr)
iris %>% dplyr::group_by(Species) %>% skim()
── Data Summary ────────────────────────
                             Value
Name                    Piped data
Number of rows                 150
Number of columns                5
                                  
Column type frequency:            
  numeric                        4
                                  
Group variables            Species

── Variable type: numeric ──────────────────────────────────────────────────────
   skim_variable Species    n_missing complete_rate  mean    sd    p0   p25
 1 Sepal.Length  setosa             0             1 5.01  0.352   4.3  4.8 
 2 Sepal.Length  versicolor         0             1 5.94  0.516   4.9  5.6 
 3 Sepal.Length  virginica          0             1 6.59  0.636   4.9  6.22
 4 Sepal.Width   setosa             0             1 3.43  0.379   2.3  3.2 
 5 Sepal.Width   versicolor         0             1 2.77  0.314   2    2.52
 6 Sepal.Width   virginica          0             1 2.97  0.322   2.2  2.8 
 7 Petal.Length  setosa             0             1 1.46  0.174   1    1.4 
 8 Petal.Length  versicolor         0             1 4.26  0.470   3    4   
 9 Petal.Length  virginica          0             1 5.55  0.552   4.5  5.1 
10 Petal.Width   setosa             0             1 0.246 0.105   0.1  0.2 
11 Petal.Width   versicolor         0             1 1.33  0.198   1    1.2 
12 Petal.Width   virginica          0             1 2.03  0.275   1.4  1.8 
     p50   p75  p100 hist 
 1  5     5.2    5.8 ▃▃▇▅▁
 2  5.9   6.3    7   ▂▇▆▃▃
 3  6.5   6.9    7.9 ▁▃▇▃▂
 4  3.4   3.68   4.4 ▁▃▇▅▂
 5  2.8   3      3.4 ▁▅▆▇▂
 6  3     3.18   3.8 ▂▆▇▅▁
 7  1.5   1.58   1.9 ▁▃▇▃▁
 8  4.35  4.6    5.1 ▂▂▇▇▆
 9  5.55  5.88   6.9 ▃▇▇▃▂
10  0.2   0.3    0.6 ▇▂▂▁▁
11  1.3   1.5    1.8 ▅▇▃▆▁
12  2     2.3    2.5 ▂▇▆▅▇
```

**Comment by elinw** [comment]
Still happening for me ... 
```
> iris %>% dplyr::group_by(Species) %>% skim()
── Data Summary ────────────────────────
                           Values    
Name                       Piped data
Number of rows             150       
Number of columns          5         
_______________________              
Column type frequency:               
  numeric                  4         
________________________             
Group variables            Species   

── Variable type: numeric ──────────────────────────────────────────────────────────────────
   skim_variable Species    n_missing complete_rate  mean    sd    p0   p25   p50   p75
 * <chr>         <fct>          <int>         <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
 1 Sepal.Length  setosa             0             1 5.01  0.352   4.3  4.8   5     5.2 
 2 Sepal.Length  versicolor         0             1 5.94  0.516   4.9  5.6   5.9   6.3 
 3 Sepal.Length  virginica          0             1 6.59  0.636   4.9  6.22  6.5   6.9 
 4 Sepal.Width   setosa             0             1 3.43  0.379   2.3  3.2   3.4   3.68
 5 Sepal.Width   versicolor         0             1 2.77  0.314   2    2.52  2.8   3   
 6 Sepal.Width   virginica          0             1 2.97  0.322   2.2  2.8   3     3.18
 7 Petal.Length  setosa             0             1 1.46  0.174   1    1.4   1.5   1.58
 8 Petal.Length  versicolor         0             1 4.26  0.470   3    4     4.35  4.6 
 9 Petal.Length  virginica          0             1 5.55  0.552   4.5  5.1   5.55  5.88
10 Petal.Width   setosa             0             1 0.246 0.105   0.1  0.2   0.2   0.3 
11 Petal.Width   versicolor         0             1 1.33  0.198   1    1.2   1.3   1.5 
12 Petal.Width   virginica          0             1 2.03  0.275   1.4  1.8   2     2.3 
    p100 hist 
 * <dbl> <chr>
 1   5.8 ▃▃▇▅▁
 2   7   ▂▇▆▃▃
 3   7.9 ▁▃▇▃▂
 4   4.4 ▁▃▇▅▂
 5   3.4 ▁▅▆▇▂
 6   3.8 ▂▆▇▅▁
 7   1.9 ▁▃▇▃▁
 8   5.1 ▂▂▇▇▆
 9   6.9 ▃▇▇▃▂
10   0.6 ▇▂▂▁▁
11   1.8 ▅▇▃▆▁
12   2.5 ▂▇▆▅▇

```

**Comment by elinw** [comment]
Okay whatever wasn't working before is working now.

**Pull request merged**
