### PR TITLE
Adds support for predicates (Issue #611)

### PR DESCRIPTION
**Pull request by brodz**
I gave fixing #611 a try. As predicates were introduced in tidyselect 1.0 this changes the required tidyselect version.

### CODE REVIEW

**Comment by elinw** [comment]
Thanks! 

The question I have is whether we test for version of tidyselect or if we force everyone to update.  The tidyverse updates break a lot of things, and I'd prefer that skimr remain usable for users who can't update for that reason.

**Comment by michaelquinn32** [comment]
LGTM.

I'm fine with the version bump. I think it's preferable to a version-based check on the behavior of the package. I realize that this puts some overhead on users, but everyone will have to update eventually.

**Comment by michaelquinn32** [comment]
Thanks for taking care of this!

**Comment by elinw** [comment]
Thinking about it I'm basically sure that one way or another probably the dplyr and other updates  have essentially forced a lot of other minimum versions. 

@brodz Do you want to add yourself as a contributor in the Description file?

**Comment by brodz** [comment]
@elinw I added myself as a contributor.

**Pull request merged**
