### PR TITLE
data.table aware

### LINKED ISSUE #621: data.table + dtplyr throws `lazy_dt()` error when running skim()
Summary:
* running `skim(DT)` where `DT` is a `data.table` produces pesky warnings. 
* The use of `dplyr` functions on a `data.table` requires some special considerations to avoid typical `lazy_dt()` warnings. 

> Warning: You are using a dplyr method on a raw data.table, which will call the
> * data frame implementation, and is likely to be inefficient.
> *
> * To suppress this message, either generate a data.table translation with
> * `lazy_dt()` or convert to a data frame or tibble with
> * `as.data.frame()`/`as_tibble()`.

# Reproducible example

## Setup
```
library(skimr)
library(data.table)

## ensure warnings are not silenced
options(warn = 1)

## create a simple data.table
DT_letters <- data.table(abc = letters)
```

## skimming works as expected, no warnings
```
skim(DT_letters)
```

## if `dtplyr` is loaded, warnings are thrown
```
library(dtplyr)
skim(DT_letters)
```

### PR DESCRIPTION
**Pull request by rsaporta**
# Making skimr data.table aware

## Summary
1. include key in output
2. no pesky warnings when `dtplyr` is loaded (closes #621 )

#### 1. include key in output
* if `data` is a `data.table` summary_df will include the `key`, defaulting to `NULL` if no `key` is set (this latter part matches the output of `data.table::key(data)`
* if `data` is **not** a `data.table`, there is no change to `summary_df`
* if `data` was a `data.table` and converted to either `data.frame` or `tibble`, then behavior of skimr is unchanged.  (several test outputs added to confirm)

#### 2. no pesky warnings when `dtplyr` is loaded
* The warnings are a function of standard dplyr/dtplyr behavior. 
* Resolved by creating `skim_by_type.data.table`

### tests:
* Several sample outputs and tests created

### CODE REVIEW

**Comment by elinw** [comment]
Thank you for this, I think it makes a lot of sense for us to support data.table cleanly.

**Review by michaelquinn32 — CHANGES_REQUESTED** [review]
This all really great! Thank you.

I've noticed a couple of style issues here along with my other comments. Could you please call `styler::style_pkg()` to clean these up?

**Comment by elinw** [comment]
@rsaporta Are you able to do the requested changes? Also you can add yourself as a contributor in the DESCRIPTION file.

**Comment by elinw** [comment]
Do we really need to export `dt_key()`?

**Comment by elinw** [comment]
@rsaporta  Are you able to update your branch?  Or would you rather have us take care of it?

**Comment by elinw** [comment]
I'm closing this in favor of https://github.com/ropensci/skimr/pull/633  ... I'm still not sure if we need the @export.

**Pull request closed without merging**
