### PR TITLE
Since knitr v1.29, knitr::kable() will add the table caption if provided

### PR DESCRIPTION
**Pull request by yihui**
Two tests in this package need to be updated accordingly.

This is because you provided the caption to `knitr::kable()`: https://github.com/ropensci/skimr/blob/b8be86090de8c5daf52f062f260aa5694880c994/R/skim_print.R#L166

In previous versions of **knitr**, the caption was silently ignored, which was not a good idea. Since **knitr** 1.29, it has changed (https://github.com/yihui/knitr/pull/1830). It will be great if you could update your tests accordingly. Thank you very much!

### CODE REVIEW

**Comment by michaelquinn32** [comment]
The remaining issue is related to r-lib/roxygen2/issues/707. Not sure what to do about it. Otherwise, I think we can merge. @elinw is that alright with you?

**Comment by elinw** [comment]
Yes that looks good to me.

**Comment by elinw** [comment]
I believe that I addressed that problem of the linked files in a number of other cases. Not in an ideal way but workable.

**Comment by elinw** [comment]
It seems to me that we might need to run separate tests with different knitr versions because we don't want to force people who don't have the ability to update to update knitr in order to use skimr.  I wouldn't want to introduce a new minimum version requirement just to get our tests to pass.

**Comment by elinw** [comment]
Please see https://github.com/ropensci/skimr/pull/597
@yihui  Shall we add you as a contributor?

By the way this support of captions is great and I'll eventually add it to the documentation for skimr.

**Comment by yihui** [comment]
@elinw Sure! My contribution is quite trivial, though. Thank you!

**Pull request merged**
