### PR TITLE
Output README to github_document

### PR DESCRIPTION
**Pull request by Bisaloo**
This produces an output with nice syntax highlighting

### CODE REVIEW

**Comment by elinw** [comment]
@michaelquinn32  This seems good, but strangely enough when I try it locally the rendering fails.

**Comment by Bisaloo** [comment]
@elinw, strange. I'm not sure what could be wrong. Can you share the exact error message please?

**Comment by michaelquinn32** [comment]
Is this a versioning issue? What branch is everyone on?

**Comment by elinw** [comment]
I'm on develop, so v1.  

> pandoc: Could not fetch https://ropensci.org/public_images/ropensci_footer.png
> TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "ropensci.org" 443
> Error: pandoc document conversion failed with error 67
> 

works fine with md_document.

**Comment by Bisaloo** [comment]
That's strange indeed. I'm not sure what's going on. I'll keep thinking about it.

I'm on `develop` as well.

**Comment by michaelquinn32** [comment]
What pandoc version is everyone on? Pandoc self_contained behavior can be finicking at times, especially in its ability to read from http during rendering. Check with: `pandoc --version`

**Comment by elinw** [comment]
‘1.19.2.1’   I used rmarkdown::pandoc_version()

**Comment by Bisaloo** [comment]
pandoc 2.4 here

**Pull request closed without merging**
