### PR TITLE
Updates due to changes in dplyr and related packages

### PR DESCRIPTION
**Pull request by elinw**
These almost all have to do with printing issues.  In some cases I'm proposing that we say either way is okay (this is because before tibbles would print a `*` at the head of the row numbers column.
#582

### CODE REVIEW

**Comment by elinw** [comment]
Basically I'd like to get the relatively simple ones fixed before dealing with the hard ones. I don't love version testing but I don't think it is worth it to do more.

**Comment by michaelquinn32** [comment]
This is good. Everything still passes for the old version of dplyr. I'm going to install v1 and start with rest of the test failures.

**Comment by elinw** [comment]
The other two failures are both from the same cause ... it's really one right now because the other one is skipped.  But solving one will mean we can stop skipping.

**Comment by michaelquinn32** [comment]
This doesn't really fix the problem (skimr needs to work correctly with vctrs), but our tests pass again.

**Comment by elinw** [comment]
Okay so I think we are aware of the issue for developers but for the people who are just using skimr it now works with both old and new versions of tibble and dplyr as far as we know.

**Comment by elinw** [comment]
The vignette build is failing on travis (which has the old version of the tidyverse) but passing on appveyor (which has the new one).

**Pull request merged**
