### PR TITLE
Allow zero length sfl for a variable type.

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by elinw** [comment]
See #577

**Comment by elinw** [comment]
Why are we removing withr?

**Comment by michaelquinn32** [comment]
We're not! Notice that it is currently listed as both suggested and imported. We only need one of these, so I'm dropping it from Suggests:

**Comment by elinw** [comment]
This is failing on appveyor with this error

> E> C:/Rtools/mingw_32/bin/g++ -std=gnu++11  -I"c:/R/include" -DNDEBUG          -O2 -Wall  -mtune=core2 -c conditions.cpp -o conditions.o
> E> C:/Rtools/mingw_32/bin/g++ -std=gnu++11  -I"c:/R/include" -DNDEBUG          -O2 -Wall  -mtune=core2 -c filter.cpp -o filter.o
> E> C:/Rtools/mingw_32/bin/g++ -std=gnu++11  -I"c:/R/include" -DNDEBUG          -O2 -Wall  -mtune=core2 -c funs.cpp -o funs.o
> E> C:/Rtools/mingw_32/bin/g++ -std=gnu++11  -I"c:/R/include" -DNDEBUG          -O
> Execution halted
> Command exited with code 1
> 7z a failure.zip *.Rcheck\*
> 

I'm going to merge because it seems unrelated to skimr.

**Pull request merged**
