### PR TITLE
Refactor summary() to separate compute and print

### PR DESCRIPTION
**Pull request by michaelquinn32**
This is intended to go after #676

It handles one of the refactorings mentioned in #667

### CODE REVIEW

**Comment by elinw** [comment]
Is the problem that led us to add https://github.com/ropensci/skimr/pull/677/files#diff-bc0bfdd73cb8cd74ba6bd991f16df8dbb07a2e4a3eeae24fd3a1a8180f75f479L56
fixed?  

Also  it's really helpful to return something that allows you to test if there is a result or NULL.  Similar to always testing for a result versus error versus empty after a query.  A lot of R code fails to do this and it causes problems later. 

That said I really disliked the way it was working before so I'm happy to see the refactor!

**Comment by michaelquinn32** [comment]
Since everything is being moved to pillar, and we are no longer inspecting the formatted string to remove metadata, it should be safe to enable crayon again. FWIW, I confirmed that it's working correcting on my windows 11 desktop (with colorized output).

**Comment by elinw** [comment]
I'm going to try this on my mac and also on the server.

**Comment by michaelquinn32** [comment]
Sorry, I didn't see a comment on width. Do you mind reminding me? Thanks!

**Comment by elinw** [comment]
We had added the rule width parameter (that controls the horizontal line at the top of the printed skims) in response to a user request shown in the linked issue.  I think we should still allow control of that.

**Comment by michaelquinn32** [comment]
Thanks!

You can still set the summary rule width, but I'll fix the other issue related to table header width soon.
https://github.com/ropensci/skimr/issues/684

**Comment by michaelquinn32** [comment]
Can we merge and then I'll take on the issue with the header width soon?

**Comment by elinw** [comment]
Sure

**Pull request merged**
