### PR TITLE
Make skim_tee acknowledge ... for tidyselect

### PR DESCRIPTION
**Pull request by dpprdan**
`skim_tee()` currently ignores the `...` argument and returns the printed
output of the full `.data`

Example from current master branch (`ropensci/skimr@cb7c34a`):

``` r
library(skimr, warn.conflicts = FALSE)

skim_tee(iris, Species)
#> Skim summary statistics
#>  n obs: 150 
#>  n variables: 5 
#> 
#> -- Variable type:factor --------------------------------------------------------------
#>  variable missing complete   n n_unique                       top_counts
#>   Species       0      150 150        3 set: 50, ver: 50, vir: 50, NA: 0
#>  ordered
#>    FALSE
#> 
#> -- Variable type:numeric -------------------------------------------------------------
#>      variable missing complete   n mean   sd  p0 p25  p50 p75 p100
#>  Petal.Length       0      150 150 3.76 1.77 1   1.6 4.35 5.1  6.9
#>   Petal.Width       0      150 150 1.2  0.76 0.1 0.3 1.3  1.8  2.5
#>  Sepal.Length       0      150 150 5.84 0.83 4.3 5.1 5.8  6.4  7.9
#>   Sepal.Width       0      150 150 3.06 0.44 2   2.8 3    3.3  4.4
#>      hist
#>  <U+2587><U+2581><U+2581><U+2582><U+2585><U+2585><U+2583><U+2581>
#>  <U+2587><U+2581><U+2581><U+2585><U+2583><U+2583><U+2582><U+2582>
#>  <U+2582><U+2587><U+2585><U+2587><U+2586><U+2585><U+2582><U+2582>
#>  <U+2581><U+2582><U+2585><U+2587><U+2583><U+2582><U+2581><U+2581>
```

<details>

<summary>equivalent testthat test</summary>

Or alternatively with one of the tests in this PR:

``` r
library(testthat, warn.conflicts = FALSE)
test_that("skim_tee prints only selected columns, but returns full object", {
  expect_output(skim_tee(iris, Species), "^(?s)(?!.*Petal).*$", perl = TRUE)
})
#> Error: Test failed: 'skim_tee prints only selected columns, but returns full object'
#> * `skim_tee\(iris, Species\)` does not match "^(?s)(?!.*Petal).*$".
#> Actual value: "Skim summary statistics\\n n obs: 150 \\n n variables: 5 \\n\\n-- Variable type:factor --------------------------------------------------------\\n variable missing complete   n n_unique                       top_counts\\n  Species       0      150 150        3 set: 50, ver: 50, vir: 50, NA: 0\\n ordered\\n   FALSE\\n\\n-- Variable type:numeric -------------------------------------------------------\\n     variable missing complete   n mean   sd  p0 p25  p50 p75 p100     hist\\n Petal\.Length       0      150 150 3\.76 1\.77 1   1\.6 4\.35 5\.1  6\.9 <U\+2587><U\+2581><U\+2581><U\+2582><U\+2585><U\+2585><U\+2583><U\+2581>\\n  Petal\.Width       0      150 150 1\.2  0\.76 0\.1 0\.3 1\.3  1\.8  2\.5 <U\+2587><U\+2581><U\+2581><U\+2585><U\+2583><U\+2583><U\+2582><U\+2582>\\n Sepal\.Length       0      150 150 5\.84 0\.83 4\.3 5\.1 5\.8  6\.4  7\.9 <U\+2582><U\+2587><U\+2585><U\+2587><U\+2586><U\+2585><U\+2582><U\+2582>\\n  Sepal\.Width       0      150 150 3\.06 0\.44 2   2\.8 3    3\.3  4\.4 <U\+2581><U\+2582><U\+2585><U\+2587><U\+2583><U\+2582><U\+2581><U\+2581>"
```
</details>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language EN                          
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2019-03-14                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source                         
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)                 
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.1)                 
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.1)                 
#>  cli           1.0.1.9000 2019-01-28 [1] Github (r-lib/cli@94e2fc5)     
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                 
#>  desc          1.2.0      2018-10-25 [1] Github (r-lib/desc@7c12d36)    
#>  devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                 
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                 
#>  dplyr         0.8.0.1    2019-02-15 [1] CRAN (R 3.5.2)                 
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.5.2)                 
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                 
#>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)                 
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.1)                 
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                 
#>  knitr         1.22       2019-03-08 [1] CRAN (R 3.5.2)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                 
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.1)                 
#>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                 
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                 
#>  processx      3.3.0      2019-03-10 [1] CRAN (R 3.5.2)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                 
#>  purrr         0.3.1      2019-03-03 [1] CRAN (R 3.5.2)                 
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                 
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.1)                 
#>  remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                 
#>  rlang         0.3.1      2019-01-08 [1] CRAN (R 3.5.2)                 
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.5.1)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                 
#>  skimr       * 1.0.5      2019-03-10 [1] Github (ropensci/skimr@cb7c34a)
#>  stringi       1.3.1      2019-02-13 [1] CRAN (R 3.5.2)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                 
#>  testthat    * 2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                 
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                 
#>  tidyr         0.8.3      2019-03-01 [1] CRAN (R 3.5.2)                 
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                 
#>  usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                 
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                 
#>  xfun          0.5        2019-02-20 [1] CRAN (R 3.5.2)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                 
#> 
#> [1] D:/Users/Daniel/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

</details>

Now with this PR applied

``` r
library(skimr, warn.conflicts = FALSE)
skim_tee(iris, Species)
#> Skim summary statistics
#>  n obs: 150 
#>  n variables: 5 
#> 
#> -- Variable type:factor --------------------------------------------------------------
#>  variable missing complete   n n_unique                       top_counts
#>   Species       0      150 150        3 set: 50, ver: 50, vir: 50, NA: 0
#>  ordered
#>    FALSE
```

### CODE REVIEW

**Comment by elinw** [comment]
Oh that's interesting.  That's also true in v2.

**Comment by elinw** [comment]
So to get a passing test you'll need to do the code in a way that doesn't generate histograms either by just selecting Species or by creating a custom skim by setting hist = NULL.

**Comment by elinw** [comment]
Updated PR with tests and news https://github.com/ropensci/skimr/pull/417

**Comment by dpprdan** [comment]
> So to get a passing test you'll need to do the code in a way that doesn't generate histograms either by just selecting Species or by creating a custom skim by setting hist = NULL.

Why is that? I don't yet understand why a `skim_with(numeric = list(hist = NULL))` is necessary in the test in #417. Or is this just due to the trouble with the UTF-8 chars that make up the histogram (on windows)?

**Comment by elinw** [comment]
Yes it is due to the UTF-8 characters which don't work in data frames on Windows (see readme) which is why those tests fail. Some of these tests we skip for Windows but in this case the histograms aren't relevant to the issue.

**Comment by elinw** [comment]
@michaelquinn32 @dpprdan  I'm going to merge the v1 version later today unless I hear otherwise from you -- I need to merge it before I merge the other v1 issue because I started 1.06 news here.  Also @dpprdan  I'll add you to contributors unless you don't want that.   Then I'll work on porting both to v2.

**Comment by michaelquinn32** [comment]
Feel free to merge. Thanks Daniel!

**Pull request merged**
